name: Push & PR to the main branch

on: push

jobs:
  lint:
    name: Passbolt CE Rootless-${{ matrix.rootless}} ${{ matrix.test_name }}
    runs-on: ruby/setup-ruby@v1
    strategy:
      matrix:
        test_name:
          [
            "docker_image",
            "docker_runtime",
            "docker_runtime_no_envs",
            "docker_runtime_with_passbolt_php",
          ]
        rootless: [true, false]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - env:
          PASSBOLT_FLAVOUR: "ce"
          ROOTLESS: ${{ matrix.rootless }}
          TEST_NAME: ${{ matrix.test_name }}
        with:
          ruby-version: "3.4.1"
        run: |
          bundle install
          bundle exec rake spec:$TEST_NAME
