on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: upload linux artifact
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref }} docker-compose/docker-compose-ce.yaml docker-compose/docker-compose-pro.yaml docker-compose/docker-compose-dev.yml

