on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docker-compose/docker-compose-ce.yaml
          asset_name: docker-compose-ce.yaml
          asset_content_type: text/plain
