on:
  push:
    tags:
      - '*'
jobs:
  create-shasums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd docker-compose
          sha512sum docker-compose-ce.yaml | awk '{print $1}' > docker-compose-ce-SHASUM.txt &&
          sha512sum docker-compose-pro.yaml | awk '{print $1}' > docker-compose-pro-SHASUM.txt &&
          sha512sum docker-compose-dev.yml | awk '{print $1}' > docker-compose-dev-SHASUM.txt
          sha512sum docker-compose-ce-postgresql.yml | awk '{print $1}' > docker-compose-ce-postgresql-SHASUM.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "docker-compose/docker-compose-*.y*ml, docker-compose/*SHASUM.txt"
